const users = require('./users')
const oauthGoogle = require('./oAuth2')
const auth = require('./auth')
const gtp = require('./gtp')
const galeries = require('./galleries')
const event = require('./event')
const village = require('./village')
const culinary = require('./culinary')
const worship = require('./worship')
const homestay = require('./homestay')
const souvenir = require('./souvenir')
const kotaKabKec = require('./kotaKabKec')
const attraction = require('./attraction')
const package = require('./package')
const reservation = require('./reservation')
const chat = require('./chat')
const messages = require('./messages')
const facility = require('./facility')
const referral = require('./referral')
const integration = require('./integration')

const router = {}

router.users = users
router.oauthGoogle = oauthGoogle
router.auth = auth
router.gtp = gtp
router.galeries = galeries
router.event = event
router.village = village
router.culinary = culinary
router.worship = worship
router.homestay = homestay
router.souvenir = souvenir
router.kotaKabKec = kotaKabKec
router.attraction = attraction
router.package = package
router.reservation = reservation
router.chat = chat
router.messages = messages
router.facility = facility
router.referral = referral
router.integration = integration

module.exports = router